config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  get "about", to: "pages#about"
  get "contact", to: "pages#contact"

  get 'feed' => 'posts#feed'

  resources :posts, only: [:show, :index] do
    collection do
      match 'search' => 'posts#search', via: [:get, :post], as: :search
    end
  end
  resources :categories
  resources :messages, only: [:new, :create]
  resources :subscribers, only: [:create, :destroy]
  get '/subscribers/unsubscribe/:signature' => 'subscribers#unsubscribe', as: 'unsubscribe'

  namespace :admin do
    get '/', to: 'dashboard#home'
    get 'site_posts', to: 'dashboard#site_posts'
    resources :posts do
      collection do
        match 'search' => 'posts#search', via: [:get, :post], as: :search
        get 'site_posts'
      end
      member do
        patch 'publish' => 'posts#update'
        patch 'auto_save' => 'posts#update'
      end
    end
    resources :users
    resources :categories
    resources :images
    resources :messages, only: [:index, :show, :destroy]
    resources :message_options, only: [:new, :show, :create]
    resources :subscribers, only: [:index, :show, :destroy]
    resources :themes, except: [:index]
    resources :menus
    get "contact", to: "pages#contact"
    patch 'auto_update_post' => 'posts#auto_update'
    patch 'clear_auto_saved_post' => 'posts#clear_auto_saved_post'
    post "create_image", to: "images#create"
    post "destroy_image", to: "images#destroy"
  end
end

app/views/shared/_ad_tile.html.haml
%li.tile.card-full
  %script{:async => "", :src => "//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"}
  / The Realistic Organizer
  %ins.adsbygoogle{"data-ad-client" => "ca-pub-7600043945930923", "data-ad-format" => "auto", "data-ad-slot" => "7538925094", :style => "display:block"}
  :javascript
    (adsbygoogle = window.adsbygoogle || []).push({});

app/views/shared/_ad_tile_footer_1.html.haml
%li.tile.card-full
  %script{:async => "", :src => "//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"}
  / The Realistic Organizer Footer 1
  %ins.adsbygoogle{"data-ad-client" => "ca-pub-7600043945930923", "data-ad-format" => "auto", "data-ad-slot" => "4166656291", :style => "display:block"}
  :javascript
    (adsbygoogle = window.adsbygoogle || []).push({});

%li.tile.card-full
  %script{:async => "", :src => "//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"}
  / Footer Ad
  %ins.adsbygoogle{"data-ad-client" => "ca-pub-8810425887317356", "data-ad-format" => "auto", "data-ad-slot" => "2572883225", :style => "display:block"}
  :javascript
    (adsbygoogle = window.adsbygoogle || []).push({});

app/views/shared/_ad_tile_footer_2.html.haml
%li.tile.card-full
  %script{:async => "", :src => "//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"}
  / The Realistic Organizer Footer 2
  %ins.adsbygoogle{"data-ad-client" => "ca-pub-7600043945930923", "data-ad-format" => "auto", "data-ad-slot" => "2550322299", :style => "display:block"}
  :javascript
    (adsbygoogle = window.adsbygoogle || []).push({});

app/views/shared/_index.html.haml
%ul.index_row
  -if cat.posts
    - cat.posts.published.limit(limit).each do |post|
      = render partial: "shared/tile", locals: { p: post, cat: cat }

app/views/shared/_message_modal.html.haml
%input#modal-message.modal-state{:type => "checkbox"}/
.modal-window
  .modal-inner
    %label.modal-close{:for => "modal-message"}
    For work inquiries please fill out our more detailed form.
    =link_to "Detailed Form", new_message_path, class: "btn"
    %hr
    =simple_form_for :message, url: messages_path , method: :post do |f|
      =f.input :name, label: false, placeholder: "Name"
      =f.input :email, label: false, placeholder: "Email"
      =f.input :body, as: :text, label: false, placeholder: "Enter your message here..."
      =f.submit "Submit"

app/views/shared/_page_header.html.haml
.page_header{style: "background: #{@category.tag_color if @category}"}
  .left
    %h2.thin= title.upcase
    .details
  .right

app/views/shared/_tile.html.haml
%li.tile.card-full{style: "background-image: url('#{attachment_url(p, :image, :fill, 200, 200)}')"}
  =link_to p do
    %span.overlay
    .content
      %h3= p.short_title.upcase
      %small= "#{ time_ago_in_words p.published_at if p.published? } ago."
  %span.plus{style: "background-color:  #{cat.tag_color unless cat.nil? }"}
    = embed_svg "plus.svg"
  .popout{style: "background-color: #{cat.tag_color unless cat.nil? }"}
    =link_to ("http://pinterest.com/pin/create/button/?url=#{request.original_url}&media=https://s3-us-west-2.amazonaws.com/real-org-images/store/#{p.shared_image.id}?fit=crop&fm=jpg&h=1200&w=750&description=#{p.title}"), target: "_blank" do
      .fa.fa-pinterest-square
    =link_to "javascript:void(0)", target: "_blank" do
      .fa.fa-facebook-square.facebook-link{ id: "#{ post_url(p) }" }
    =link_to "https://plus.google.com/share?url=#{post_url(p)}", target: "_blank" do
      .fa.fa-google-plus-square
    =link_to p do
      Read