config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  get "about", to: "pages#about"
  get "contact", to: "pages#contact"

  get 'feed' => 'posts#feed'

  resources :posts, only: [:show, :index] do
    collection do
      match 'search' => 'posts#search', via: [:get, :post], as: :search
    end
  end
  resources :categories
  resources :messages, only: [:new, :create]
  resources :subscribers, only: [:create, :destroy]
  get '/subscribers/unsubscribe/:signature' => 'subscribers#unsubscribe', as: 'unsubscribe'

  namespace :admin do
    get '/', to: 'dashboard#home'
    get 'site_posts', to: 'dashboard#site_posts'
    resources :posts do
      collection do
        match 'search' => 'posts#search', via: [:get, :post], as: :search
        get 'site_posts'
      end
      member do
        patch 'publish' => 'posts#update'
        patch 'auto_save' => 'posts#update'
      end
    end
    resources :users
    resources :categories
    resources :images
    resources :messages, only: [:index, :show, :destroy]
    resources :message_options, only: [:new, :show, :create]
    resources :subscribers, only: [:index, :show, :destroy]
    resources :themes, except: [:index]
    resources :menus
    get "contact", to: "pages#contact"
    patch 'auto_update_post' => 'posts#auto_update'
    patch 'clear_auto_saved_post' => 'posts#clear_auto_saved_post'
    post "create_image", to: "images#create"
    post "destroy_image", to: "images#destroy"
  end
end

app/models/message_option.rb
class MessageOption < ActiveRecord::Base
  serialize :times
  serialize :spaces
end

app/models/message_options.rb
class MessageOptions < ActiveRecord::Base
  serialize :times
  serialize :spaces
end

app/controllers/admin/message_options_controller.rb
class Admin::MessageOptionsController < AdminController
  def new
    @message_option = MessageOption.new
  end

  def show
    @message_option = MessageOption.find(params[:id])
  end

  def create
    @message_option = MessageOption.new(
      spaces: new_message_option_params[:spaces].split(","),
      times: new_message_option_params[:times].split(",")
    )
    @message_option.save
    redirect_to admin_message_option_path(@message_option), notice: "New Message Options saved."
  end

  private

    def new_message_option_params
      params.require(:message_option).permit(:spaces, :times)
    end
end

app/views/admin/message_options/new.html.haml
=render "nav"
%h3 Message Options
=simple_form_for [:admin, @message_option] do |f|
  =f.input :spaces, label: "Spaces - Eg. Living Room, Kitchen", placeholder: "Spaces (comma separated)"
  =f.input :times, label: "Times - Eg. 8a to 12p, 12p to 4p", placeholder: "Times (comma separated)"
  =f.submit "Save"

app/views/admin/message_options/show.html.haml
=render "nav"
%h3 Message Options
%h3 Time Slots
%ul
-@message_option.times.each do |time|
  %li=time
%h3 Spaces
%ul
-@message_option.spaces.each do |space|
  %li=space

=link_to "Edit", new_admin_message_option_path