config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  get "about", to: "pages#about"
  get "contact", to: "pages#contact"

  get 'feed' => 'posts#feed'

  resources :posts, only: [:show, :index] do
    collection do
      match 'search' => 'posts#search', via: [:get, :post], as: :search
    end
  end
  resources :categories
  resources :messages, only: [:new, :create]
  resources :subscribers, only: [:create, :destroy]
  get '/subscribers/unsubscribe/:signature' => 'subscribers#unsubscribe', as: 'unsubscribe'

  namespace :admin do
    get '/', to: 'dashboard#home'
    get 'site_posts', to: 'dashboard#site_posts'
    resources :posts do
      collection do
        match 'search' => 'posts#search', via: [:get, :post], as: :search
        get 'site_posts'
      end
      member do
        patch 'publish' => 'posts#update'
        patch 'auto_save' => 'posts#update'
      end
    end
    resources :users
    resources :categories
    resources :images
    resources :messages, only: [:index, :show, :destroy]
    resources :message_options, only: [:new, :show, :create]
    resources :subscribers, only: [:index, :show, :destroy]
    resources :themes, except: [:index]
    resources :menus
    get "contact", to: "pages#contact"
    patch 'auto_update_post' => 'posts#auto_update'
    patch 'clear_auto_saved_post' => 'posts#clear_auto_saved_post'
    post "create_image", to: "images#create"
    post "destroy_image", to: "images#destroy"
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  attachment :image

  has_many :post_categories
  has_many :posts, through: :post_categories

  scope :alphabetical, -> { order("name ASC") }
  scope :regular, -> { where.not(name: "Recent Projects")}

  def nice_name
    name.gsub(/%20/, " ")
  end

  def post_image
    posts.last.image unless self.posts.empty?
  end

  def generate_link
    "link_to '#{self.name}', category_path(#{self.id})"
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  before_filter :set_category, only: [:show, :edit, :update, :destroy]
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path, notice: "Category was successfully created"
    else
      render :new, notice: "Your category was not created"
    end
  end

  def show
  end

  def update
    @category = Category.friendly.find(params[:id])

    if @category.update(category_params)
      redirect_to admin_categories_path, notice: "#{@category.name} was successfully updated"
    else
      redirect_to :back
    end
  end

  def index
    @categories = Category.alphabetical
  end

  def edit
  end

  def destroy
    @category.destroy
    @category.posts.collect do |p|
      p.move_to_uncategorized
    end

    redirect_to admin_categories_path, notice: "#{@category.name} was successfully deleted"
  end

  private

  def set_category
    @category = Category.friendly.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :menu_slot, :tag_color, :image, :remove_image)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @q = Post.ransack(params[:q])
    @category = Category.friendly.find(params[:id])
  end

  def index
    @categories = Category.alphabetical.regular.page params[:page]
  end

end

app/views/admin/categories/_form.html.haml
.category-form
  = simple_form_for [:admin, @category] do |f|
    .clearfix
      .card
        -if @category.image_id?
          #image.card_image{style: "background: url(#{ attachment_url(@category, :image, :fit, 300, 300) }) no-repeat center; background-size: cover"}
        -else
          #image.card_image{style: "background: url('http://placehold.it/300x300&text=No%20Image) no-repeat center; background-size: cover"}
        = f.input :remove_image, as: :boolean, label: "Remove Image" if @category.image_id?
        = f.attachment_field :image, direct: true, presigned: true, class: "image_upload"
      .post_info
        = f.input :name
        .clear
          .tag-color= f.input :tag_color
          .menu-slot= f.input :menu_slot, collection: Menu.last.slots.each_with_index.map { |slot, index| [slot, (index + 1) ]}
        = f.submit "Update", class: "button btn-inline", style: "margin-right: 10px;"
  -if @category.id
    .clear
      = button_to "Delete Category", admin_category_path(@category), class: "clear button btn-inline btn-warning", method: :delete, data: { confirm: "Are you sure" }
    %hr.thick

app/views/admin/categories/edit.haml
=render "admin/nav"
=render "form"
-if @category.posts
  =render partial: "admin/posts/index", locals: { posts: @category.posts }

app/views/admin/categories/index.haml
=render "admin/nav"
.body
  .index
    - @categories.each do |c|
      .card
        =link_to edit_admin_category_path(c), style: "color: white;" do
          -if c.image_id?
            .image{style: "background: url('#{attachment_url(c, :image, :fill, 200, 200)}') no-repeat center; background-size: cover"}
          -else
            .image{style: "background: url('http://placehold.it/200x200&text=No%20Image') no-repeat center; background-size: cover"}
          .content
            .title
              %strong=c.nice_name
            %hr.thick{style: "border-color: #{c.tag_color}"}
            = "#{c.posts.count} posts"
        %ul.action
          %li
            =link_to category_path(c) do
              %i.fa.fa-location-arrow
          %li
            =link_to edit_admin_category_path(c) do
              %i.fa.fa-pencil

app/views/admin/categories/new.html.haml
=render "admin/nav"
=render "form"

app/views/admin/categories/show.haml
=render "admin/nav"
%h3= @category.nice_name
%br
=render partial: "admin/posts/index", locals: { posts: @category.posts }