config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  get "about", to: "pages#about"
  get "contact", to: "pages#contact"

  get 'feed' => 'posts#feed'

  resources :posts, only: [:show, :index] do
    collection do
      match 'search' => 'posts#search', via: [:get, :post], as: :search
    end
  end
  resources :categories
  resources :messages, only: [:new, :create]
  resources :subscribers, only: [:create, :destroy]
  get '/subscribers/unsubscribe/:signature' => 'subscribers#unsubscribe', as: 'unsubscribe'

  namespace :admin do
    get '/', to: 'dashboard#home'
    get 'site_posts', to: 'dashboard#site_posts'
    resources :posts do
      collection do
        match 'search' => 'posts#search', via: [:get, :post], as: :search
        get 'site_posts'
      end
      member do
        patch 'publish' => 'posts#update'
        patch 'auto_save' => 'posts#update'
      end
    end
    resources :users
    resources :categories
    resources :images
    resources :messages, only: [:index, :show, :destroy]
    resources :message_options, only: [:new, :show, :create]
    resources :subscribers, only: [:index, :show, :destroy]
    resources :themes, except: [:index]
    resources :menus
    get "contact", to: "pages#contact"
    patch 'auto_update_post' => 'posts#auto_update'
    patch 'clear_auto_saved_post' => 'posts#clear_auto_saved_post'
    post "create_image", to: "images#create"
    post "destroy_image", to: "images#destroy"
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  require "uri"
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :user
  has_many :post_categories
  has_many :categories, through: :post_categories, counter_cache: true
  attachment :image
  attachment :pinterest_image
  is_impressionable :counter_cache => true

  validates :title, presence: true

  default_scope -> { order('created_at DESC') }
  scope :site_post, -> { where(site_post: true) }
  scope :regular_post, -> { where(site_post: false) }
  scope :published, -> { where.not(published_at: nil).where(site_post: false).order('published_at DESC') }
  scope :published_non_projects, -> { joins(:categories).where.not("categories.name" => "Recent Projects").published }

  accepts_nested_attributes_for :post_categories

  def slug_candidates
    [
      :title,
      [:title, :created_at],
    ]
  end

  def self.check_for_new_posts
    # Check for post published within last 24 hours
    recent_posts = self.where("published_at > '#{24.hours.ago}'")
    # Send post notification email
    recent_posts.each do |post|
      post.send_email unless post.email_sent?
    end
  end

  def short_title
    title.truncate(100)
  end

  def encoded_title
    URI.encode self.title
  end

  def publish!
    update(published_at: Time.now)
    self.save
    check_for_categories
  end

  def save_as_draft!
    update(published_at: nil)
    check_for_categories
  end

  def published?
    published_at != nil
  end

  def check_for_categories
    if self.categories.empty? && self.site_post == false
      uncategorized = Category.find_by_name("Uncategorized")
      PostCategory.create(post_id: self.id, category_id: uncategorized.id)
    end
  end

  def email_sent?
    email_sent_at != nil
  end

  def body_without_images
    require 'nokogiri'
    doc = Nokogiri::HTML(self.body)
    doc.search("img").remove
    doc.to_html
  end

  def strip_body_tags
    doc = Nokogiri::HTML(self.body)
    body = doc.xpath("//text()").to_s
    return body
  end

  def strip_and_truncate(length)
    doc = Nokogiri::HTML(self.body)
    body = doc.xpath("//text()").to_s
    body[0...length]
  end

  def shared_image
    if pinterest_image_id?
      pinterest_image
    else
      image
    end
  end

  def send_email
    # check again to see if post is still marked published
    if published_at != nil
      recent_projects = Category.find_by_name("Recent Projects")
      unless self.categories.include? recent_projects or self.site_post? or self.email_sent?
        SiteMailer.post_notification(self)
        self.email_sent_at = Time.now
        self.save
      end
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController
  layout 'post', only: [:new, :edit]
  before_action :set_post, only: [:edit, :update, :updatish, :show, :destroy]
  skip_before_filter :verify_authenticity_token, only: [:auto_save, :auto_update]


  def new
    # Create the post so that autosave has an id to save to
    @post = Post.new
    @post.body = session[:auto_saved_post] if session[:auto_saved_post]
    @categories = Category.all
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      if params[:category_ids]
        params[:category_ids].each do |category_id|
          PostCategory.create(
            post_id: @post.id,
            category_id: category_id
          )
        end
      end
      session[:auto_saved_post] = nil
      @post.publish! if publishing?
      @post.save_as_draft! if drafting?
      redirect_to admin_post_path(@post), notice: "#{@post.title} was susccessfully created"
    else

      redirect_to new_admin_post_path,  alert: "Post could not be saved"
    end
  end

  def show
  end

  def index
    if params[:posts]
      posts = params[:posts]
      @posts = posts.regular_post
    else
      @posts = Post.regular_post.page params[:page]
    end
    if session[:auto_saved_post]
      @session_post = Post.new(title: "Autosaved Draft", body: session[:auto_saved_post])
      @posts.unshift(@session_post)
    end
  end

  def search
    if params[:q]
      @posts = @q.result(distinct: true)
    else
      @posts = Post.first(3)
    end
  end

  def site_posts
    @posts = Post.site_post.page params[:page]
  end

  def edit
    @categories = Category.all
  end

  def update
    @post.update(post_params)
    if @post.save
      @post.publish! if publishing?
      @post.save_as_draft! if drafting?
      if params[:category_ids]
        PostCategory.where(post_id: @post.id).delete_all
        params[:category_ids].each do |category_id|
        PostCategory.create(
          post_id: @post.id,
          category_id: category_id
          )
        end
      end
      session[:auto_saved_post] = nil
      redirect_to admin_post_path(@post), notice: "#{@post.title} was susccessfully updated"
    end
  end

  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to admin_posts_path, alert: "#{@post.title} was successfully deleted" }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end

  def auto_update
    if params[:id]
      post = Post.find(params[:id])
      post.update(body: params[:body])
    else
      # If there is no id save the body to the session
      puts "Autosaved"
      session[:auto_saved_post] = params[:body]
      puts session[:auto_saved_post]
    end
    render nothing: true, status: 200
  end

  def clear_auto_saved_post
    session[:auto_saved_post] = nil
    redirect_to :back, alert: "Autosaved Draft deleted"
  end

  private

  def set_post
    @post = Post.friendly.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :user_id, :image, :remove_image, :pinterest_image, :remove_pinterest_image, :site_post, post_categories_attributes: [:post_id])
  end

  def publishing?
    params["commit"] == "Publish"
  end

  def drafting?
    params["commit"] == "Save as Draft"
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :verify_and_set_post, only: :show

  def feed
    @posts= Post.all.limit(10)
    respond_to do |format|
      format.rss { render :layout => false }
    end
  end

  def show
    @post = Post.friendly.find(params[:id])
    @categories = Category.regular
    @subscriber = Subscriber.new

    impressionist(@post)
    @post.impressionist_count(filter: :session_hash)
  end

  def index
    if params[:posts]
      posts = params[:posts]
      @posts = posts.published_non_projects.page params[:page]
    elsif params[:month]
      @posts = Post.published.group_by { |p| p.published_at.strftime("%B") }[params[:month]]
    else
      @posts = Post.published_non_projects.page params[:page]
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def search
    if params[:q]
      @posts = @q.result(distinct: true)
    else
      @posts = Post.first(3)
    end
  end

  private

  def verify_and_set_post
    @post = Post.friendly.find(params[:id])
    unless @post.published?
      redirect_to root_path, notice: "This post is not available"
    end
  end
end

app/views/posts/_archives.html.haml
.blog-archive-block.card
  %h3 BLOG ARCHIVE
  %hr
  %ul
    -Date::MONTHNAMES.slice(1,12).each do |m|
      %li.archive-month
        %strong
          =link_to m, posts_path(month: m), remote: true
        %ul.archive_list{id: m}

app/views/posts/_archives_list.html.haml
- @posts.each do |post|
  %li
    =link_to "#{post.title} (#{post.published_at.year})", post

app/views/posts/_category_block.html.haml
.category-block
  %ul
    - i = 0
    - @categories.each do |c|
      - i += 1
      = link_to c do
        -if c.image_id?
          %li{style: "background: url('#{attachment_url(c, :image, :fill, 100, 100)}') no-repeat center; background-size: cover; color: #{c.tag_color}"}
        -else
          %li{style: "background: url('http://placehold.it/100x100/#{c.tag_color.gsub("#", "")}/fff/&text=#{c.nice_name.parameterize}') no-repeat center; background-size: cover; color: #{c.tag_color}"}
        = c.nice_name.upcase

app/views/posts/_poster.html.haml
.poster{style: "background-image: url('#{attachment_url(post, :image, :fill, 800, 500)}')"}
  .overlay
    .poster-icons.icon-list
      =link_to ("http://pinterest.com/pin/create/button/?url=#{request.original_url}&media=https://s3-us-west-2.amazonaws.com/real-org-images/store/#{@post.shared_image.id}?fit=crop&fm=jpg&h=1200&w=750&description=#{@post.title}"), target: "_blank" do
        .fa.fa-pinterest-square.fa-3x.pinterest
      =link_to "javascript:void(0)", target: "_blank" do
        .fa.fa-3x.fa-facebook-square.facebook.facebook-link{ id: "#{ post_url(@post) }" }
      =link_to "https://plus.google.com/share?url=#{post_url(@post)}", target: "_blank" do
        .fa.fa-3x.fa-google-plus-square.google-plus
    .content
      .text
        =link_to @post do
          %h2{style: "color: white"}= @post.title
      - post.categories.each do |category|
        =link_to category do
          %span.tag.poster-tag{style: "background: #{category.tag_color}"}= category.nice_name.upcase

app/views/posts/_related_block.html.haml
.related-blogs-block
  %h3 RELATED POSTS
  %hr
  %ul
    - i = 0
    - p.categories.each do |cat|
      - if i < 3
        - cat.posts.last(3).each do |post|
          = render partial: "shared/tile", locals: { p: post, cat: cat }
          - i += 1
    = render partial: "shared/ad_tile"

app/views/posts/_sidebar.html.haml
.welcome.card
  =link_to about_path do
    = image_tag attachment_url(@user, :image, :fill, 300, 300), class: 'welcome-picture'
    .greeting
      %span.meet MEET
      %span.name= @user.first_name.upcase
      %p= @user.bio
  .call-to-action
  .modal
    %label{:for => "modal-message"}
      .btn-outline.btn-full.modal-trigger{style: "text-align: center"} GET IN TOUCH
      =render "shared/message_modal"
  .spacer
  .icon-list
    =link_to "http://feeds.feedburner.com/therealisticorganizer/lDaA", rel: "alternate", type: "application/rss+xml", target: "_blank" do
      .fa.fa-rss.fa-3x
    -unless @theme.pinterest.blank?
      =link_to @theme.pinterest, target: "_blank" do
        .fa.fa-pinterest-square.fa-3x
    -unless @theme.facebook.blank?
      =link_to @theme.facebook, target: "_blank" do
        .fa.fa-facebook-square.fa-3x
    -unless @theme.instagram.blank?
      =link_to @theme.instagram, target: "_blank" do
        .fa.fa-instagram.fa-3x
    -unless @theme.google_plus.blank?
      =link_to @theme.google_plus, target: "_blank" do
        .fa.fa-google-plus-square.fa-3x
    -unless @theme.blog_lovin.blank?
      =link_to @theme.blog_lovin, target: "_blank" do
        .fa.fa-heart.fa-3x
    .spacer
    %h3 NEVER MISS A POST
    = simple_form_for @subscriber do |f|
      = f.input :email, label: false, placeholder: "Email"
      = f.submit "SUBSCRIBE", class: "btn btn-full", style: "border: none;"
    .spacer
  = render partial: "posts/category_block"

app/views/posts/_social_card.html.haml
#fb-root
:javascript
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&appId=714905915289688&version=v2.0";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
.social_card
  .icon-list
    =link_to ("http://pinterest.com/pin/create/button/?url=#{request.original_url}&media=https://s3-us-west-2.amazonaws.com/real-org-images/store/#{@post.shared_image.id}?fit=crop&fm=jpg&h=1200&w=750&description=#{@post.encoded_title}"), target: "_blank" do
      .fa.fa-pinterest-square.fa-3x.pinterest
    =link_to "javascript:void(0)", target: "_blank" do
      .fa.fa-3x.fa-facebook-square.facebook.facebook-link{ id: "#{ post_url(@post) }" }
    =link_to "https://plus.google.com/share?url=#{post_url(@post)}", target: "_blank" do
      .fa.fa-3x.fa-google-plus-square.google-plus

app/views/posts/index.haml
.container
  = render "nav"
  = render partial: "shared/page_header", locals: { title: "Posts", q: @q }
  .index
    %ul.index_row
      - @posts.each do |p|
        =render partial: "shared/tile", locals: { p: p, cat: p.categories.first }
.pagination
  = paginate @posts
= render "footer"

app/views/posts/index.html.haml
.container
  = render "nav"
  = render partial: "shared/page_header", locals: { title: "Posts", q: @q }
  .index
    %ul.index_row
      - @posts.each do |p|
        =render partial: "shared/tile", locals: { p: p, cat: p.categories.first }
.pagination
  = paginate @posts
= render "footer"

app/views/posts/index.js.erb
var month = "#<%= Date::MONTHNAMES[@posts.first.published_at.month] %>"
if ($(month).parent('li').find('.archive_list li').length > 0 ) {
  $(month).parent('li').find('.archive_list li').remove()
} else {
  $("<%= j(render partial: "archives_list", locals: { posts: @posts }) %>").appendTo(month)
}

app/views/posts/search.html.haml
.container
  = render "nav"
  = render partial: "shared/page_header", locals: { title: "Search", q: @q }
  .index
    %ul.index_row
      - @posts.each do |p|
        =render partial: "shared/tile", locals: { p: p, cat: p.categories.first }
= render "footer"

app/views/posts/show.haml
.container
  = render "nav"
  .main
    :erb
      <script>
        window.fbAsyncInit = function() {
          FB.init({
            appId      : '714905915289688',
            xfbml      : true,
            version    : 'v2.2'
          });
        };

        (function(d, s, id){
           var js, fjs = d.getElementsByTagName(s)[0];
           if (d.getElementById(id)) {return;}
           js = d.createElement(s); js.id = id;
           js.src = "//connect.facebook.net/en_US/sdk.js";
           fjs.parentNode.insertBefore(js, fjs);
         }(document, 'script', 'facebook-jssdk'));
      </script>
    =render partial: "poster", locals: { post: @post }
    .blog.card
      =@post.body.html_safe
      -if @post.published_at > Date.new(2015/3/1)
        = attachment_image_tag @theme, :signature_image
    .index
      %ul.index_row_wide
        = render partial: "shared/ad_tile_footer_1"
        = render partial: "shared/ad_tile_footer_2"
    .comment.card
      .comment-header
        %h2 COMMENTS
      %hr
      #disqus_thread
        :coffee
          # Required - Replace example with your forum shortname
          disqus_shortname = "therealisticorganizer"
          disqus_identifier = '/organized-weekly-dinners/'

          ### * * DON'T EDIT BELOW THIS LINE * * ###
          do ->
            dsq = document.createElement('script')
            dsq.type = 'text/javascript'
            dsq.async = true
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js'
            (document.getElementsByTagName('head')[0] or document.getElementsByTagName('body')[0]).appendChild dsq
            return

  .sidebar
    =render partial: "sidebar", locals: { p: @post }
    =render partial: "related_block", locals: { p: @post }
    =render partial: "archives", locals: { posts: @posts }
= render "social_card"
= render "footer"

=content_for :javascript do
  :javascript
    $('[title*=\'Pin\']').each(function() {
      var array, source, url;
      array = $(this).attr('src').split('/');
      source = array[array.length - 2];
      url = 'http://pinterest.com/pin/create/button/?url=#{request.original_url}&media=https://s3-us-west-2.amazonaws.com/real-org-images/store/' + source + '?fit=crop&fm=jpg&h=1200&w=750&description=#{@post.encoded_title}';
      return $(this).parent('.fr-tag').append('<a class=\'pinterest-tag\' target=\'_blank\' href=\'' + url + '\'><i class=\'fa fa-pinterest-square pinterest fa-3x\'></i></a>');
    });